# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Api::V1::State.create(name: "Arizona", abbreviation: "AZ")
# Api::V1::State.create(name: "Arkansas", abbreviation: "AR")
# Api::V1::State.create(name: "California", abbreviation: "CA")
# Api::V1::State.create(name: "Colorado", abbreviation: "CO")
# Api::V1::State.create(name: "Connecticut", abbreviation: "CT")
# Api::V1::State.create(name: "Delaware", abbreviation: "DE")
# Api::V1::State.create(name: "District of Columbia", abbreviation: "DC")
# Api::V1::State.create(name: "Florida", abbreviation: "FL")
# Api::V1::State.create(name: "Georgia", abbreviation: "GA")
# Api::V1::State.create(name: "Hawaii", abbreviation: "HI")
# Api::V1::State.create(name: "Idaho", abbreviation: "ID")
# Api::V1::State.create(name: "Illinois", abbreviation: "IL")
# Api::V1::State.create(name: "Indiana", abbreviation: "IN")
# Api::V1::State.create(name: "Iowa", abbreviation: "IA")
# Api::V1::State.create(name: "Kansas", abbreviation: "KS")
# Api::V1::State.create(name: "Kentucky", abbreviation: "KY")
# Api::V1::State.create(name: "Louisiana", abbreviation: "LA")
# Api::V1::State.create(name: "Maine", abbreviation: "ME")
# Api::V1::State.create(name: "Maryland", abbreviation: "MD")
# Api::V1::State.create(name: "Massachusetts", abbreviation: "MA")
# Api::V1::State.create(name: "Michigan", abbreviation: "MI")
# Api::V1::State.create(name: "Minnesota", abbreviation: "MN")
# Api::V1::State.create(name: "Mississippi", abbreviation: "MS")
# Api::V1::State.create(name: "Missouri", abbreviation: "MO")
# Api::V1::State.create(name: "Montana", abbreviation: "MT")
# Api::V1::State.create(name: "Nebraska", abbreviation: "NE")
# Api::V1::State.create(name: "Nevada", abbreviation: "NV")
# Api::V1::State.create(name: "New Hampshire", abbreviation: "NH")
# Api::V1::State.create(name: "New Jersey", abbreviation: "NJ")
# Api::V1::State.create(name: "New Mexico", abbreviation: "NM")
# Api::V1::State.create(name: "New York", abbreviation: "NY")
# Api::V1::State.create(name: "North Carolina", abbreviation: "NC")
# Api::V1::State.create(name: "North Dakota", abbreviation: "ND")
# Api::V1::State.create(name: "Ohio", abbreviation: "OH")
# Api::V1::State.create(name: "Oklahoma", abbreviation: "OK")
# Api::V1::State.create(name: "Oregon", abbreviation: "OR")
# Api::V1::State.create(name: "Pennsylvania", abbreviation: "PA")
# Api::V1::State.create(name: "Rhode Island", abbreviation: "RI")
# Api::V1::State.create(name: "South Carolina", abbreviation: "SC")
# Api::V1::State.create(name: "South Dakota", abbreviation: "SD")
# Api::V1::State.create(name: "Tennessee", abbreviation: "TN")
# Api::V1::State.create(name: "Texas", abbreviation: "TX")
# Api::V1::State.create(name: "Utah", abbreviation: "UT")
# Api::V1::State.create(name: "Vermont", abbreviation: "VT")
# Api::V1::State.create(name: "Virginia", abbreviation: "VA")
# Api::V1::State.create(name: "West Virginia", abbreviation: "WA")
# Api::V1::State.create(name: "Wisconsin", abbreviation: "WV")
# Api::V1::State.create(name: "Wyoming", abbreviation: "WI")

Api::V1::Property.create(address: "4096 Caissons Ct, Enola, PA, 17025", rent: 1250, paid: true, expenses: 850, state_id: 39)